# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on: push

jobs:
  build-macos:
    runs-on: macos-13
    steps:
      - name: Checkout repository with tags
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Import Developer Certificate
        run: |
          echo "$MACOS_CERTIFICATE_BASE64" | base64 --decode > certificate.p12
          security create-keychain -p "" build.keychain
          security import certificate.p12 -k build.keychain -P "$MACOS_CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain
          security unlock-keychain -p "" build.keychain
        env:
          MACOS_CERTIFICATE_PASSWORD: ${{ secrets.MACOS_CERTIFICATE_PASSWORD }}
          MACOS_CERTIFICATE_BASE64: ${{ secrets.MACOS_CERTIFICATE_BASE64 }}

      - name: Test codesign
          shell: bash
          run: |
            export BUILD_TYPE=RelWithDebInfo
            export BUILD_DIR=./build
            security find-certificate -c "$APPLE_DEVELOPER_IDENTITY"
          env:
            APPLE_DEVELOPER_IDENTITY: ${{ secrets.APPLE_DEVELOPER_IDENTITY }}
            APPLE_ID: ${{ secrets.APPLE_ID}}
            APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
            TEAM_ID: ${{ secrets.TEAM_ID }}
